### ISSUE TITLE
我新加ldapns.schema的时候。出现了如下问题。

### ISSUE THREAD

**Issue by 1551462073** [sous-chefs/openldap#119]
slaptest -f /etc/ldap/ldap.conf -F /etc/ldap/slapd.d
        60cb4c31 /etc/ldap/schema/ldapns.schema: line 32 objectclass: AttributeType not found: "host"
        slaptest: bad configuration directory!

我不确定问题是处在哪里，麻烦指教下

**Comment by ramereth** [comment]
Can you please elaborate more how you're using the cookbook to get this error?

**Comment by 1551462073** [comment]
这是我参考操作的网站：https://www.cnblogs.com/cishi/p/9160554.html。期待您的回复

**Comment by ramereth** [comment]
Can you please provide some example Chef code which replicates the issue?
